Add hint for :one and :many queries with no output columns
pggen surfaces constraint violations for a query that returns no rows but
is marked :one or :many instead of :exec, like:

    -- name: Foo :one
    UPDATE foo SET bar = 1;

pggen needs at least one output column result type for :one and :many queries.
Postgres happily provides the types even if the query failed. Since we have the
row types, we can ignore any errors from running the query because pggen only
cares about the row type, not actually running the query. The problem is if
the user's query omits a RETURNING clause for UPDATE or INSERT statement. pggen
doesn't get any column types because there are no output columns, so pggen
assumes the query failed and surfaces the error.

The new error message adds a HINT line.

    parse template query file "file.sql":
    infer typed named query CreateItem:
    infer output types for query: fetch field descriptions:
    null value in column "display_name" of relation "item_current" violates not-null constraint
        DETAIL: Failing row contains (0, 0, /items/).
        TableName: item_current
        HINT: if the main statement is an UPDATE or INSERT ensure that you have
              a RETURNING clause (this query is marked :one).
              Use :exec if you don't need the query output.
        ERROR: null value in column "display_name" of relation "item_current" violates not-null constraint (SQLSTATE 23502)